name: attendance_mobile
description: An Offline-First HR Attendance Mobile App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Packages
  flutter_bloc: ^8.1.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
